name: miniprogui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc_concurrency: 0.2.0
  collection: 1.16.0
  easy_localization: 3.0.1
  fast_immutable_collections: 7.3.1
  fluent_ui: 3.12.0
  fluentui_system_icons: 1.1.169
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  freezed_annotation: 2.0.3
  get_it: 7.2.0
  lottie: 1.3.0
  package_info_plus: 1.4.2
  shared_preferences: 2.0.15
  system_theme: 2.0.0
  wakelock: 0.6.1+2

dev_dependencies:
  build_runner: 2.1.11
  freezed: 2.0.3+1
  lint: 1.8.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/en.json
    - assets/translations/nl.json